name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.5.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  percent_indicator: ^4.2.5
  url_launcher: ^6.3.1
  flutter_widget_from_html: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
